fix error while starting SASL client
While connecting, error like this was raised:

TTransportException: TTransportException(type=1, message="Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server krbtgt/XX@XXYYZZ.HADOOP not found in Kerberos database)'")

This was caused by a sasl_client parameter setting error.